services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flask_api:
    build:
      context: .
      dockerfile: flask/Dockerfile
    ports:
      - "6000:5000"
    depends_on:
      - redis
    volumes:
      - ./app/screenshots:/app/screenshots

  celery_worker:
    build:
        context: .
        dockerfile: celery/Dockerfile
    command: ["celery", "-A", "celery_app.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app/screenshots:/app/screenshots

  flower:
      image: mher/flower
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
      depends_on:
        - redis
        - celery_worker
      ports:
        - "5555:5555"

